version: '3'

services:
  mqtt:
    image: eclipse-mosquitto:1.5
    ports:
      - 1883:1883
    networks:
      - mqtt-network
    restart: always
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  adapter:
    depends_on:
      - mqtt
    build:
      context: ./adapter
    networks:
      - mqtt-network
    restart: always
    image: adapter
    command: ["python3", "-u", "main.py"]

networks:
  mqtt-network:
