version: '3'

services:
  mqtt:
    image: eclipse-mosquitto:1.5
    ports:
      - 1883:1883
    networks:
      - mqtt-network
    restart: always
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  adapter:
    image: adapter
    depends_on:
      - mqtt
      - influxdb
    build:
      context: ./adapter
    environment:
      - DEBUG_DATA_FLOW=True
    networks:
      - mqtt-network
      - db-network
    restart: always
    command: ["python3", "-u", "main.py"]

  influxdb:
    image: influxdb:1.8
    ports:
      - 8086:8086
    networks:
      - db-network
      - grafana-network
    restart: always
    volumes:
      - influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    networks:
      - grafana-network
    ports:
      - 80:3000
    environment:
      - GF_SECURITY_ADMIN_USER=asistent
      - GF_SECURITY_ADMIN_PASSWORD=grafanaSPRC2021
    restart: always
    volumes:
      - grafana-provisioning:/var/lib/grafana

networks:
  mqtt-network:
  db-network:
  grafana-network:

volumes:
  influxdb:
  grafana-provisioning:
